dataset:
  data_name: "mnist"
  root: '../../Data'
  download: true
  simulated: true
  simulated_root: './simulated/'
  distribution_type: 'iid' # options: iid, non_iid_class, non_iid_dir
  class_per_client: 2
  alpha: 0.9
  min_size: 1
  

server: 
  clients_num: 100
  rounds: 100
  clients_per_round: 10
  random_select: true
  aggregation_rule: fedavg
  aggregation_detail: equal
  loss_fn: "cross_entropy"  # options: cross_entropy, mse; defualt is cross entropy
  test_interval: 1
  model_name: LeNet5
  records_save_folder: './results/'
  


client:
  batch_size: 32
  test_batch_size: 32
  local_epoch: 3
  loss_fn: "cross_entropy"  # options: cross_entropy, mse; defualt is cross entropy
  optimizer:
    type: "Adam" # options: Adam, SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0
  
log_level: "DEBUG" #options: DEBUG INFO
seed: 0
is_visualization: true # if true, start the visdom first